// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWvgj9huyW8Zu-1RQG4gYNq2KEhoDUsfU',
    appId: '1:54799040792:web:3a7a734fc51f1d43771e6d',
    messagingSenderId: '54799040792',
    projectId: 'hotpotproject-a11fb',
    authDomain: 'hotpotproject-a11fb.firebaseapp.com',
    storageBucket: 'hotpotproject-a11fb.appspot.com',
    measurementId: 'G-T8NMERHY3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7g7Jl18DZkPBtTgf0uNhIReOM-gGemLU',
    appId: '1:54799040792:android:9e00055276c79f80771e6d',
    messagingSenderId: '54799040792',
    projectId: 'hotpotproject-a11fb',
    storageBucket: 'hotpotproject-a11fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-fyppR82lg7OEghzBsahAV306w_mcXc',
    appId: '1:54799040792:ios:ed606c910137e28c771e6d',
    messagingSenderId: '54799040792',
    projectId: 'hotpotproject-a11fb',
    storageBucket: 'hotpotproject-a11fb.appspot.com',
    iosBundleId: 'com.example.hotpotproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-fyppR82lg7OEghzBsahAV306w_mcXc',
    appId: '1:54799040792:ios:78145641255ba1ff771e6d',
    messagingSenderId: '54799040792',
    projectId: 'hotpotproject-a11fb',
    storageBucket: 'hotpotproject-a11fb.appspot.com',
    iosBundleId: 'com.example.hotpotproject.RunnerTests',
  );
}
